import type { Metadata } from "next";
import "../sass/main.scss";
import PageRender from "./PageRender";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <PageRender>{children}</PageRender>
      </body>
    </html>
  );
}
